version: "3"
# define all services
services:

  #  The Application
  app:
    # we want to use the image which is build from our Dockerfile
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
    - ./cli.cc:/root/programs/code-rawtherapee/rtgui/main-cli.cc
    - ./input:/root/input
